platform :ios , '8.0' 
target 'ChatKit-alipay' do
# ignoring warning from pods
inhibit_all_warnings!

#=========================================================
#======================== Lib Dependency =================
#=========================================================
pod 'ChatKit', :path => '../'

#=========================================================
#======================== Demo Dependency ================
#=========================================================

pod "CYLTabBarController", "~> 1.9.0"
pod "CYLTableViewRowAction", "1.0.0"
pod 'TWMessageBarManager'
pod 'MLPAutoCompleteTextField'
#pod 'MLeaksFinder'
pod 'FTPopOverMenu'
pod 'RedpacketAliAuthLib'
pod "FXForms", "~> 1.2.14"

end


target 'ChatKit-JDpay' do
    # ignoring warning from pods
    inhibit_all_warnings!
    
    #=========================================================
    #======================== Lib Dependency =================
    #=========================================================
    pod 'ChatKit', :path => '../'
    
    #=========================================================
    #======================== Demo Dependency ================
    #=========================================================
    
    pod "CYLTabBarController", "~> 1.9.0"
    pod "CYLTableViewRowAction", "1.0.0"
    pod 'TWMessageBarManager'
    pod 'MLPAutoCompleteTextField'
    #pod 'MLeaksFinder'
    pod 'FTPopOverMenu'
    pod 'RedpacketLib'
    pod "FXForms", "~> 1.2.14"
    
end
